version: "3"
services:
  graphql-basketball-api:
    image: volkansaydam/graphql-basketball-api
    ports:
      - 8080:8080
    networks:
      - basketball-mysql
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8
    networks:
      - basketball-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=basketball
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5

networks:
  basketball-mysql: